export enum Types {
  APP_IPHONE = 'APP/IPHONE',
  APP_ADD_TO_CART = 'APP/ADD/TO/CART',
  APP_REMOVE = 'APP/REMOVE',
  APP_PLUS_CART = 'APP/PLUS/CART',
  APP_MINUS_CART = 'APP/MINUS/CART',
  APP_AUTH = 'APP/AUTH',
  APP_CATEGORIES = 'APP/CATEGORIES',
  APP_SORT_BY = 'APP/SORY/BY',
  APP_LOADING = 'APP/LOADING',
  APP_IS_LOADER = 'APP/IS/LOADER',
  APP_LOGOUT = 'APP/LOGOUT',
  APP_CART = 'APP/CART'
}

